
-- local trouble = require("trouble.providers.telescope")
--
-- require("telescope").setup {
--   defaults = {
--     mappings = {
--       i = {
--         ["<esc>"] = require("telescope.actions").close,
--         ["<C-h>"] = "which_key",
--         ["<c-t>"] = trouble.open_with_trouble,
--       },
--       n = {
--         ["<c-t>"] = trouble.open_with_trouble
--       }
--     },
--   },
-- }

-- require("telescope").load_extension("emoji")
--
-- require("telescope").load_extension("fzf")
